module.exports = [
    "!commands",
    "!nicememe",
    "!discord",
    "!donate",
    "!wat",
    "!pingu",
    "!steif",
    "!ping",
    "!hackfleischhassenderzerhacker",
    "!lotto",
    "!giveaway",
    "!fail",
    "!monsterfail",
];